### ISSUE TITLE
Lightbeam Deletes functionality not querying API correctly

### ISSUE THREAD

**Issue by emondal1026** [edanalytics/lightbeam#21]
I am in the process of building out delete functionality for DPS to delete descriptors from their ODS.  I want to leverage the lightbeam delete functionality, but it seems that lightbeam is not correctly querying the API.

On the server request logs, we can see a request come through like so:

/data/v3/ed-fi/programTypeDescriptors?codeValue=504&namespace=uri://dpsk12.org/programTypeDescriptor&shortDescription=106

These parameters are not valid to be used against the API as per swagger.  This request will return the whole set of PorgramTypeDescriptors that exist in the ODS. so returns a 200 response, but does not subset the descriptors as perhaps intended. 

This results in lightbeam not being able to find a 1-1 match for payload and record with this being an output:

lightbeam INFO (reason: [multiple matching payloads found in API]; instances: 2)

There are also no subsequent DELETE requests to the API as per the access logs, so lightbeam is definitely stopping after this point.

**Comment by tomreitz** [comment]
@emondal1026 I wanted to check in here (and sorry about the delay!), were you using lightbeam [version 0.1.0](https://github.com/edanalytics/lightbeam/blob/main/CHANGELOG.md#v010) or greater? I believe since that version this should actually be resolved (via the code [here](https://github.com/edanalytics/lightbeam/blob/221b7b6a918ab72bb5366e90d675cc85410ac4e5/lightbeam/delete.py#L67-L78) and [here](https://github.com/edanalytics/lightbeam/blob/221b7b6a918ab72bb5366e90d675cc85410ac4e5/lightbeam/delete.py#L135-L147)).

I just tested this locally by (a) sending a new descriptor value, (b) fetching to make sure it was there, (c) deleting based on a payload with the codeValue, and finally (d) fetching again to make sure it had been removed. All seemed to be working fine.

**Comment by tomreitz** [comment]
I'm closing this issue after confirming with Eshara that the problem has indeed been fixed.
